import Vue from 'vue'
import { NavBar } from 'vant';
import { Tabbar, TabbarItem } from 'vant';
import { Search } from 'vant';
import { Grid, GridItem } from 'vant';
import { Icon } from 'vant';
import { Swipe, SwipeItem } from 'vant';
import { Divider } from 'vant';
import { Tag } from 'vant';
import { Button } from 'vant';
import { Toast } from 'vant';
import { Notify } from 'vant';
import { Field } from 'vant';
import { Sidebar, SidebarItem } from 'vant';
import { List } from 'vant';
import { Loading } from 'vant';
import { NoticeBar } from 'vant';
import { Card } from 'vant';
import { SubmitBar } from 'vant';
import { AddressEdit } from 'vant';
import { AddressList } from 'vant';
import { ActionSheet } from 'vant';
import { Image } from 'vant';

Vue.use(Image);
Vue.use(ActionSheet);
Vue.use(AddressList);
Vue.use(AddressEdit);
Vue.use(SubmitBar);
Vue.use(Card);
Vue.use(NoticeBar);
Vue.use(Loading);
Vue.use(List);
Vue.use(Sidebar);
Vue.use(SidebarItem);
Vue.use(Field);
Vue.use(Notify);
Vue.use(Button);
Vue.use(Tag);
Vue.use(Divider);
Vue.use(Swipe).use(SwipeItem);
Vue.use(Icon);
Vue.use(Grid).use(GridItem);
Vue.use(Search);
Vue.use(Tabbar).use(TabbarItem);
Vue.use(NavBar);
Vue.use(Toast);
